/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jzbyapp_myapplication_util_FactoryUtil */

#ifndef _Included_com_jzbyapp_myapplication_util_FactoryUtil
#define _Included_com_jzbyapp_myapplication_util_FactoryUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jzbyapp_myapplication_util_FactoryUtil
 * Method:    StringFromRootShell
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jzbyapp_myapplication_util_FactoryUtil_StringFromRootShell
  (JNIEnv *, jobject, jbyteArray);

JNIEXPORT jstring JNICALL Java_com_jzbyapp_myapplication_util_FactoryUtil_GetCMMacAddr
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
