//
// Created by Administrator on 2018/4/24.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <sys/wait.h>
#include <string.h>
#include "android/log.h"
#include "cm_ctrl.h"

#define MAXLINE 1024

/* Header for class com_jzbyapp_myapplication_util_FactoryUtil */

#ifndef _Included_com_jzbyapp_myapplication_util_FactoryUtil
#define _Included_com_jzbyapp_myapplication_util_FactoryUtil
#ifdef __cplusplus
extern "C" {
#endif

#define LOG_TAG "RootShell"
#define LOGD(...) __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)

/*
 * Class:     com_jzbyapp_myapplication_util_FactoryUtil
 * Method:    StringFromRootShell
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jzbyapp_myapplication_util_FactoryUtil_StringFromRootShell
  (JNIEnv *env, jobject thiz, jbyteArray data){

    char result_buf[MAXLINE], command[MAXLINE];
    char StringResult[MAXLINE] ;
    int rc = 0; // 用于接收命令返回值
    FILE *fp;

    jbyte* jbyteData = (*env)->GetByteArrayElements(env,data, NULL);
    int length = (*env)->GetArrayLength(env,data);
    memset(command, 0, MAXLINE);
    memset(result_buf,0,MAXLINE);
    memset(StringResult,0,MAXLINE);
    strncpy(command, (char*)jbyteData, length);
    LOGD("command:%s,len:%d",command,length);

    fp = popen(command, "r");
    if(NULL == fp)
    {
        LOGD("popen failed！");
        exit(1);
    }
    while(fgets(result_buf, sizeof(result_buf), fp) != NULL)
    {
        /*为了下面输出好看些，把命令返回的换行符去掉*/
//        if('\n' == result_buf[strlen(result_buf)-1])
//        {
//            result_buf[strlen(result_buf)-1] = '\0';
//        }
        strncat(StringResult, result_buf, strlen(result_buf));//
        if(strlen(StringResult) > MAXLINE){
            LOGD("StringResult is too long.");
            memset(StringResult,0,MAXLINE);
            break;
        }
//        LOGD("result_buf =%s, strlen(result_buf)=%d", result_buf,strlen(StringResult));
    }
    rc = pclose(fp);
    if(-1 == rc)
    {
        LOGD("pclose failed");
        exit(1);
    }
    LOGD("command[%s] print[%s]\n", command, StringResult);

    return (*env)->NewStringUTF(env,StringResult);
  }

/*
 * Class:     com_jzbyapp_myapplication_util_FactoryUtil
 * Method:    GetCMMacAddr
 * Signature: ()[B
 */
JNIEXPORT jstring JNICALL Java_com_jzbyapp_myapplication_util_FactoryUtil_GetCMMacAddr
        (JNIEnv *env, jobject jobject1){

    char mac[6];
    char MAC[18]={0};
    memset(mac, 0, 6);
    cm_Get_MAC_Address(mac);
    int i=0,j=0;
    for(i=0,j=0;i<6;i++)
    {
        if((mac[i]>>4&0x0f)>0x9)
        {
            MAC[j++]=((mac[i]>>4)&0x0f)-0xa+'a';
            if((mac[i]&0x0f)>0x9)
                MAC[j++]=(mac[i]&0x0f)-0xa+'a';
            else
                MAC[j++]=(mac[i]&0x0f)+'0';
        }
        else
        {
            MAC[j++]=(mac[i]>>4&0x0f)+'0';
            if((mac[i]&0x0f)>0x9)
                MAC[j++]=(mac[i]&0x0f)-0xa+'a';
            else
                MAC[j++]=(mac[i]&0x0f)+'0';
        }
        if(i!=5)
            MAC[j++]='-';
        else
            MAC[j++]='\0';
    }
    LOGD("MAC:%s",MAC);

    return (*env)->NewStringUTF(env,MAC);
}


/*
 * Class:     com_jzbyapp_myapplication_util_FactoryUtil
 * Method:    dvbNVMReadForIpanel
 * Signature: (Ljava/lang/String;I)[B
 */
//JNIEXPORT jbyteArray JNICALL Java_com_jzbyapp_myapplication_util_FactoryUtil_dvbNVMReadForIpanel
//        (JNIEnv *env, jobject thiz, jstring jstring1, jint jint1){
//
//
//}

/*
 * Class:     com_jzbyapp_myapplication_util_FactoryUtil
 * Method:    dvbNVMWriteForIpanel
 * Signature: (Ljava/lang/String;[B)I
 */
//JNIEXPORT jint JNICALL Java_com_jzbyapp_myapplication_util_FactoryUtil_dvbNVMWriteForIpanel
//        (JNIEnv *env, jobject thiz, jstring jstring1, jbyteArray data){
//
//}


#ifdef __cplusplus
}
#endif
#endif
